### ISSUE TITLE
Main Menu not appearing (launcher)

### ISSUE THREAD

**Issue by zehDonut** [bfeber/HLA-NoVR#276]
Sorry if this is a stupid question, but what am I supposed to do to start the game once I get to the title screen?
All I can see is this:
<img width="1920" alt="Half-Life  Alyx Screenshot 2024 11 29 - 14 28 34 53" src="https://github.com/user-attachments/assets/60c01506-ef80-4e53-b075-5580c06d5eeb">

I thought something was broken on my end, so I reinstalled the game and the mod, but it still looks like this.

**Comment by Berwiin** [comment]
same bro

**Comment by zehDonut** [comment]
> same bro

@Berwiin 

I found a workaround, but you need 2 screens for it:

+ Rick click on the game in steam, open properties
+ Move the properties window to a separate display
+ Start the game
+ The menu should show up on the secondary display

**Comment by Berwiin** [comment]
I'll try thank youuu

**Comment by godsSide** [comment]
> > same bro
> 
> @Berwiin
> 
> I found a workaround, but you need 2 screens for it:
> 
>     * Rick click on the game in steam, open properties
> 
>     * Move the properties window to a separate display
> 
>     * Start the game
> 
>     * The menu should show up on the secondary display

THIS WORKED THANK YOU SO MUCH!

**Comment by gb2dev** [comment]
Should be fixed mostly

**Comment by flatsiedatsie** [comment]
Still happened here just now. Ran fine the first time, but no menu after that.

Fresh install, running Windows via Parallels on Mac OS. 

- It happened after the touchpad suddenly stopped working as movement input (though it still worked in the game menu) in chapter 3. Hence the restart.
- Selecting the "reinstall mod" option did not solve it.
- The workaround mentioned above worked like a charm.
